packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  electron: true
  esbuild: true
  onnxruntime-node: true
  sharp: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - electron
  - electron-builder
  - onnxruntime-node
